from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence

from .pipeline import NarrationOptions, run_narration


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="ppt-narrator",
        description="Extract PPTX speaker notes and generate narration assets.",
    )
    parser.add_argument("pptx", type=Path, help="Input .pptx file.")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=None,
        help="Output directory. Defaults to <pptx-stem>_ppt_narrator.",
    )
    parser.add_argument(
        "--provider",
        default="dry-run",
        choices=["dry-run", "doubao"],
        help="TTS provider.",
    )
    parser.add_argument(
        "--voice",
        default="dry-run",
        help="Voice/speaker identifier passed to the provider.",
    )
    parser.add_argument(
        "--language",
        default="zh",
        help="Language hint passed to the TTS provider.",
    )
    parser.add_argument(
        "--tts-config",
        type=Path,
        default=None,
        help="Optional JSON config. Supports AiVideoClip volcengine.local.json and Studio V2 cloud config shapes.",
    )
    parser.add_argument(
        "--audio-input-dir",
        type=Path,
        default=None,
        help="Use externally generated page-001.wav/mp3/m4a audio files instead of running a TTS provider.",
    )
    parser.add_argument(
        "--doubao-resource-id",
        default="",
        help="Override X-Api-Resource-Id for Doubao TTS, for example seed-tts-2.0 or seed-icl-2.0.",
    )
    parser.add_argument(
        "--doubao-voice-mode",
        choices=["builtin", "clone", "config"],
        default="builtin",
        help="Doubao voice mode. builtin uses seed-tts-2.0 and ignores cloned speaker config unless --voice is set.",
    )
    parser.add_argument(
        "--chars-per-second",
        type=float,
        default=15.0,
        help="Dry-run narration speed used to estimate audio length.",
    )
    parser.add_argument(
        "--no-audio",
        action="store_true",
        help="Only export notes and manifest.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Allow replacing files generated by a previous run.",
    )
    parser.add_argument(
        "--slide-limit",
        type=int,
        default=None,
        help="Process only the first N slides. Useful for provider smoke tests.",
    )
    parser.add_argument(
        "--write-pptx",
        action="store_true",
        help="Write an auto-advance PPTX copy using generated per-slide audio.",
    )
    parser.add_argument(
        "--pptx-output",
        type=Path,
        default=None,
        help="Output path for --write-pptx. Defaults inside the output directory.",
    )
    parser.add_argument(
        "--advance-padding-ms",
        type=int,
        default=500,
        help="Extra milliseconds added to each slide transition after audio duration.",
    )
    parser.add_argument(
        "--pptx-audio-format",
        choices=["source", "mp3"],
        default="source",
        help="Audio format embedded into PPTX. Use mp3 for better presentation-app compatibility.",
    )
    parser.add_argument(
        "--visible-audio-icon",
        action="store_true",
        help="Place a visible audio object on each slide instead of hiding it.",
    )
    parser.add_argument(
        "--direct-audio-start",
        action="store_true",
        help="Start the embedded p:audio timing node when the slide loads. Useful for presentation-app autoplay compatibility tests.",
    )
    parser.add_argument(
        "--audio-trigger",
        choices=["media", "transition-sound"],
        default="media",
        help="How generated PPTX audio is triggered. transition-sound uses slide transition sound instead of a media object.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    options = NarrationOptions(
        input_pptx=args.pptx,
        output_dir=args.output,
        provider=args.provider,
        voice=args.voice,
        language=args.language,
        tts_config=args.tts_config,
        audio_input_dir=args.audio_input_dir,
        doubao_resource_id=args.doubao_resource_id,
        doubao_voice_mode=args.doubao_voice_mode,
        chars_per_second=args.chars_per_second,
        audio_enabled=not args.no_audio,
        overwrite=args.overwrite,
        slide_limit=args.slide_limit,
        write_pptx=args.write_pptx,
        pptx_output=args.pptx_output,
        advance_padding_ms=args.advance_padding_ms,
        pptx_audio_format=args.pptx_audio_format,
        visible_audio_icon=args.visible_audio_icon,
        direct_audio_start=args.direct_audio_start,
        audio_trigger=args.audio_trigger,
    )
    try:
        result = run_narration(options)
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    print(f"slides: {result.slide_count}")
    print(f"notes: {result.notes_markdown}")
    print(f"manifest: {result.manifest_json}")
    if result.audio_dir:
        print(f"audio: {result.audio_dir}")
    if result.narrated_pptx:
        print(f"pptx: {result.narrated_pptx}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
